name: My workflow

on: push

jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
              
      - name: Deploy to test-gh-actions.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'test-gh-actions.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
